name: Heroku publish

on:
  push:
    branches:
    - master

jobs:
  push-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push 'dist' folder to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fedora-books-backend"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
