name: Heroku publish
on:
  push:
    branches:
    - master
jobs:
  push-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Generate GraphQL code from schema.prisma
        run: npm run prisma:generate
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
      - name: Sync database schema with application
        run: npm run prisma:schema
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
      - name: Build application
        run: npm run build
      - name: Copy prisma schema to dist
        run: cp prisma/schema.prisma dist/schema.prisma
      - name: Clean node_modules without prisma
        working-directory: ./node_modules
        run: ls -A | grep -v "@prisma\|\.prisma" | xargs rm -rf 
      - name: Clean current
        run: ls -A | grep -v "dist\|node_modules" | xargs rm -rf 
      - name: Create Procfile
        run: |
          touch Procfile 
          echo "web: node dist/server.js" >> Procfile
      - name: Create package.json
        run: |
          touch package.json
          echo '{
            "name": "fedora-books-backend",
            "version": "1.0.0",
            "description": "plug package.json",
            "main": "web.js",
            "author": "laefad",
            "dependencies" : {
              "@prisma/client": "^3.14.0"
            }
          }' >> package.json
      - name: Init git
        run: git init
      - name: Push builded app to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fedora-books-backend"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_JWT_KEY: ${{secrets.JWT_KEY}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_APOLLO_KEY: ${{secrets.APOLLO_KEY}}
          HD_APOLLO_GRAPH_REF: fedora-books-backend@current
          HD_APOLLO_SCHEMA_REPORTING: true
          HD_NODE_MODULES_CACHE: false
